name: '${id}'
main: '${group}.${id}.${target}.${mainClass}'
version: '${version}'
author: M1dnight_Ninja
api-version: '1.13'
depend:
  - 'midnightcore'
commands:
  skin:
    description: 'Main SkinSetter Command'