modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="${id}"
version="${version}"
displayName="Example Mod"
logoFile="assets/${id}/icon.png"
authors="M1dnight_Ninja"
description="${description}"

[[dependencies.${id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
